export const FETCH_LEMBURAN_TODAY = 'FETCH_LEMBURAN_TODAY';
export const FETCH_LEMBURAN_MONTHLY = 'FETCH_LEMBURAN_MONTHLY';
export const FETCH_LEMBURAN_BY_APPROVAL = 'FETCH_LEMBURAN_BY_APPROVAL';
export const FETCH_LEMBURAN_BY_STATUS = 'FETCH_LEMBURAN_BY_STATUS';
export const STATUS_DATA = 'STATUS_DATA';
export const MESSAGE_DATA = 'MESSAGE_DATA';
